# Generated by Django 4.1.3 on 2025-04-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dreams/'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
