# Generated by Django 4.1.3 on 2025-04-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydream', '0002_dream_image_alter_dream_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
