# Generated by Django 4.1.3 on 2025-04-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydream', '0003_alter_dream_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='dreams/'),
        ),
    ]
