# Generated by Django 4.1.3 on 2025-03-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='work_images/')),
                ('category', models.CharField(choices=[('worklife', 'Work Life'), ('cv', 'My CV'), ('dataanalyst', 'Data Analyst')], default='worklife', max_length=20)),
            ],
        ),
    ]
