# Generated by Django 4.1.3 on 2025-04-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworklife', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
