# Generated by Django 4.1.3 on 2025-04-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworklife', '0002_alter_workexperience_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='work_videos/'),
        ),
    ]
