# Generated by Django 4.1.3 on 2025-03-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='education_images/')),
                ('category', models.CharField(choices=[('general', 'General'), ('erasmus', 'Erasmus+'), ('university', 'University'), ('data', 'Data')], default='general', max_length=20)),
            ],
        ),
    ]
