# Generated by Django 4.1.3 on 2025-04-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeducationlife', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('erasmus', 'Erasmus+'), ('university', 'University'), ('data', 'Data'), ('taekwondo', 'Taekwondo')], default='general', max_length=20),
        ),
    ]
