# Generated by Django 4.1.3 on 2025-04-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeducationlife', '0004_education_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='education/videos/'),
        ),
    ]
