# Generated by Django 4.1.3 on 2025-04-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeducationlife', '0005_alter_education_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('erasmus', 'Erasmus+'), ('university', 'University'), ('data', 'Data'), ('sports', 'Sports')], default='general', max_length=20),
        ),
    ]
