# Generated by Django 4.1.3 on 2025-04-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CengizhanGenc', '0002_alter_homepagehighlight_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagehighlight',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='homepage/'),
        ),
    ]
